[package]
name = "@datalinkhq/rbx-datalink"
description = "A futuristic and lightweight analytics platform for upcoming ROBLOX games."

version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
