[package]
name = "datalinkhq/rbx-datalink"
description = "A futuristic and lightweight analytics platform for upcoming ROBLOX games. Learn more at https://datalink.dev."
authors = ["AsyncMatrix <catbob614@gmail.com>", "DevComp <hi@devcomp.xyz>"]

version = "2.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
