local HttpService = game:GetService("HttpService")
local HttpComponent = { }

function HttpComponent:setHeaders()
	
end

function HttpComponent:getHeaders()
	
end

function HttpComponent:buildWebUri()
	
end

function HttpComponent:buildWebHeaders()
	
end

function HttpComponent:buildWebBody()
	
end

function HttpComponent:requestAsync()
	
end

function HttpComponent:start()
	
end

function HttpComponent:init()
	self._httpEnabled = HttpService.HttpEnabled
	self._headers = { }
end

return HttpComponent