name: Selene Linter

on:
  push:
    branches: [ "main", "development", "feature/*", "bugfix/*" ]
  pull_request:
    branches: [ "main", "development", "feature/*", "bugfix/*" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup Aftman toolchain
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: "0.2.7"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate Standard Library
      run: selene generate-roblox-std
    - name: Remove Submodules
      run: rm -r submodules
    - name: Run Selene
      run: |- 
        selene source
